Advent of Code 2021 - Day 11

Part 1:
Given the starting energy levels of the dumbo octopuses in your cavern, simulate 100 steps. How many total flashes are there after 100 steps?

In [40]:
import numpy as np

In [63]:
test_data = """
5483143223
2745854711
5264556173
6141336146
6357385478
4167524645
2176841721
6882881134
4846848554
5283751526"""

test_data = [item.strip() for item in test_data.split()]
test_data = [[int(char) for char in line] for line in test_data]
test_data = np.array(test_data)
test_data

array([[5, 4, 8, 3, 1, 4, 3, 2, 2, 3],
       [2, 7, 4, 5, 8, 5, 4, 7, 1, 1],
       [5, 2, 6, 4, 5, 5, 6, 1, 7, 3],
       [6, 1, 4, 1, 3, 3, 6, 1, 4, 6],
       [6, 3, 5, 7, 3, 8, 5, 4, 7, 8],
       [4, 1, 6, 7, 5, 2, 4, 6, 4, 5],
       [2, 1, 7, 6, 8, 4, 1, 7, 2, 1],
       [6, 8, 8, 2, 8, 8, 1, 1, 3, 4],
       [4, 8, 4, 6, 8, 4, 8, 5, 5, 4],
       [5, 2, 8, 3, 7, 5, 1, 5, 2, 6]])

In [64]:
with open('input_day11.txt', 'rt') as f:
    data = f.readlines()

data = [item.rstrip() for item in data]
data = [[int(char) for char in line] for line in data]
data = np.array(data)
data

array([[4, 3, 4, 1, 3, 4, 7, 6, 4, 3],
       [5, 4, 7, 7, 7, 2, 8, 4, 5, 1],
       [2, 3, 2, 2, 7, 3, 3, 8, 7, 8],
       [5, 4, 5, 3, 7, 6, 2, 5, 5, 6],
       [2, 7, 1, 8, 1, 2, 3, 4, 2, 1],
       [4, 2, 3, 7, 8, 8, 6, 1, 1, 5],
       [5, 6, 3, 1, 6, 1, 7, 1, 1, 4],
       [2, 2, 1, 7, 6, 6, 7, 2, 2, 7],
       [4, 2, 3, 6, 5, 8, 1, 2, 5, 5],
       [4, 4, 8, 2, 6, 2, 7, 6, 4, 1]])

In [89]:
x_max, y_max = np.shape(data)
x_max, y_max = x_max-1, y_max-1

def increment_step(octopi):
    
    octopi += 1

    flashers = np.argwhere(octopi == 10)
    
    if len(flashers) > 0:
        for flasher in flashers:
            increase_adjacent(tuple(flasher), octopi)

    octopi = np.where(octopi >=10, 0, octopi)
    number_of_flashes = np.count_nonzero(octopi == 0)

    if number_of_flashes == 100:
        simultaneous_flash = True
    else:
        simultaneous_flash = False

    return octopi, number_of_flashes, simultaneous_flash


def find_adjacent(octopus:tuple, octopi:np.array):
    x, y = octopus

    x_range = [x, x+1]
    y_range = [y, y+1]

    if x > 0:
        x_range.append(x-1)
    if y > 0:
        y_range.append(y-1)

    possibly_adjacent = []
    for x_a in x_range:
        for y_a in y_range:
            possibly_adjacent.append((x_a, y_a))

    adjacent_octopi = []
    for posibility in possibly_adjacent:
        try:
            _ = octopi[posibility]
            adjacent_octopi.append(posibility)
        except IndexError:
            pass
    
    adjacent_octopi.remove(octopus)

    return adjacent_octopi


def increase_adjacent(octopus: tuple, octopi: np.array):

    adjacent_octopi = find_adjacent(octopus, octopi)

    flashers = []
    for o in adjacent_octopi:
        octopi[o] += 1
        if octopi[o] == 10:
            flashers.append(o)
    
    if flashers:
        for flasher in flashers:
            increase_adjacent(flasher, octopi)
    


In [84]:
d = test_data.copy()

print(d)

total_num = 0
for n in range(100):
    d, num = increment_step(d)
    total_num += num

total_num


[[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]


1656

In [87]:
d = data.copy()

print(d)

total_num = 0
for n in range(100):
    d, num, _ = increment_step(d)
    total_num += num



[[4 3 4 1 3 4 7 6 4 3]
 [5 4 7 7 7 2 8 4 5 1]
 [2 3 2 2 7 3 3 8 7 8]
 [5 4 5 3 7 6 2 5 5 6]
 [2 7 1 8 1 2 3 4 2 1]
 [4 2 3 7 8 8 6 1 1 5]
 [5 6 3 1 6 1 7 1 1 4]
 [2 2 1 7 6 6 7 2 2 7]
 [4 2 3 6 5 8 1 2 5 5]
 [4 4 8 2 6 2 7 6 4 1]]


In [86]:
# Part 1 answer
print(total_num)

1697


Part 2: 

In [88]:
# total number of octopi
np.shape(data)[0] * np.shape(data)[1]

100

In [94]:
d = data.copy()

print(d)

total_num = 0

for n in range(500):
    d, num, s = increment_step(d)
    if s:
        print('Simultaneous flash at step: ', n+1)
    total_num += num

[[4 3 4 1 3 4 7 6 4 3]
 [5 4 7 7 7 2 8 4 5 1]
 [2 3 2 2 7 3 3 8 7 8]
 [5 4 5 3 7 6 2 5 5 6]
 [2 7 1 8 1 2 3 4 2 1]
 [4 2 3 7 8 8 6 1 1 5]
 [5 6 3 1 6 1 7 1 1 4]
 [2 2 1 7 6 6 7 2 2 7]
 [4 2 3 6 5 8 1 2 5 5]
 [4 4 8 2 6 2 7 6 4 1]]
Simultaneous flash at step:  344
Simultaneous flash at step:  354
Simultaneous flash at step:  364
Simultaneous flash at step:  374
Simultaneous flash at step:  384
Simultaneous flash at step:  394
Simultaneous flash at step:  404
Simultaneous flash at step:  414
Simultaneous flash at step:  424
Simultaneous flash at step:  434
Simultaneous flash at step:  444
Simultaneous flash at step:  454
Simultaneous flash at step:  464
Simultaneous flash at step:  474
Simultaneous flash at step:  484
Simultaneous flash at step:  494


In [ ]:
# Part 2 answer