Advent of Code 2021 - Day 4

Part 1:
The score of the winning board can now be calculated. Start by finding the sum of all unmarked numbers on that board. Then, multiply that sum by the number that was just called when the board won, to get the final score.

To guarantee victory against the giant squid, figure out which board will win first. What will your final score be if you choose that board?

In [26]:
import numpy as np

In [23]:
with open('input_day4.txt', 'rt') as f:
    data = f.readlines()

data = [item.rstrip() for item in data]

In [24]:
numbers = [int(num) for num in data[0].split(',')]
print(numbers)

[31, 50, 79, 59, 39, 53, 58, 95, 92, 55, 40, 97, 81, 22, 69, 26, 6, 23, 3, 29, 83, 48, 18, 75, 47, 49, 62, 45, 35, 34, 1, 88, 54, 16, 56, 77, 28, 94, 52, 15, 0, 87, 93, 90, 60, 67, 68, 85, 80, 51, 20, 96, 61, 66, 63, 91, 8, 99, 70, 13, 71, 17, 7, 38, 44, 43, 5, 25, 72, 2, 57, 33, 82, 78, 89, 21, 30, 11, 73, 84, 4, 46, 14, 19, 12, 10, 42, 32, 64, 98, 9, 74, 86, 27, 24, 65, 37, 41, 76, 36]


In [25]:
boards = []

for line in data[1:]:
    if line == '':
        boards.append([])
    else:
        boards[-1].append(line)

print(boards[:2])

[['31  5 70  8 88', '38 63 14 91 56', '22 67 17 47 74', '93 52 69 29 53', '33 66 64 19 73'], ['35 63 17 48 77', '25 58 33 14 96', '32 87 90 66 70', '16  4 98 72 23', '19 74 39 29 59']]


In [78]:
class Board:

    def __init__(self, contents):
        contents = [[int(num) for num in row.split()] for row in contents]
        self.board = np.array(contents)
        self.scoreboard = np.zeros(shape = np.shape(self.board))
        self.winner = False
    
    def draw_num(self, num):
        self.scoreboard = np.where(self.board == num, 1, self.scoreboard)
        self.check_bingo()

    def check_bingo(self):
        for row in self.scoreboard:
            if np.all(row == 1):
                self.winner = True
        
        for column in self.scoreboard.transpose():
            if np.all(column == 1):
                self.winner = True        


In [79]:
my_boards = []
for board in boards:
    my_boards.append(Board(board))

In [80]:
for num in numbers:
    for my_board in my_boards:
        my_board.draw_num(num)

        if my_board.winner:
            break
    
    else:
        continue    # only executed if the inner loop did NOT break

    break   # only executed if the inner loop DID break

In [83]:
my_board.scoreboard

array([[0., 1., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [0., 0., 0., 1., 0.],
       [1., 1., 0., 0., 0.]])

In [85]:
my_board.unmarked = np.where(my_board.scoreboard == 0, my_board.board, 0)
my_board.unmarked


array([[41,  0, 44,  2,  0],
       [38, 14, 19, 72, 64],
       [ 0,  0,  0,  0,  0],
       [70,  7,  1,  0, 86],
       [ 0,  0, 90, 96, 82]])

In [87]:
my_sum = np.sum(my_board.unmarked)
print(my_sum, num)

726 35


In [88]:
# Part 1 answer
print(my_sum * num)

25410


Part 2: Figure out which board will win last. Once it wins, what would its final score be?

In [107]:
my_boards = []
for board in boards:
    my_boards.append(Board(board))

for num in numbers:
    # print('Testing num: ', num)
    for my_board in my_boards:

        if not my_board.winner:
            my_board.draw_num(num)

            if my_board.winner:
                print('Got a winner!', num)

            if all([my_board.winner for my_board in my_boards]):
                break
    
    else:
        continue    # only executed if the inner loop did NOT break

    break   # only executed if the inner loop DID break

my_board.unmarked = np.where(my_board.scoreboard == 0, my_board.board, 0)
my_sum = np.sum(my_board.unmarked)
print(my_sum, num)

Got a winner! 35
Got a winner! 77
Got a winner! 77
Got a winner! 15
Got a winner! 15
Got a winner! 0
Got a winner! 0
Got a winner! 0
Got a winner! 87
Got a winner! 87
Got a winner! 93
Got a winner! 93
Got a winner! 93
Got a winner! 90
Got a winner! 90
Got a winner! 90
Got a winner! 60
Got a winner! 60
Got a winner! 60
Got a winner! 60
Got a winner! 67
Got a winner! 67
Got a winner! 68
Got a winner! 80
Got a winner! 51
Got a winner! 20
Got a winner! 96
Got a winner! 61
Got a winner! 61
Got a winner! 61
Got a winner! 61
Got a winner! 61
Got a winner! 66
Got a winner! 66
Got a winner! 63
Got a winner! 63
Got a winner! 63
Got a winner! 63
Got a winner! 63
Got a winner! 63
Got a winner! 8
Got a winner! 8
Got a winner! 8
Got a winner! 8
Got a winner! 99
Got a winner! 70
Got a winner! 70
Got a winner! 70
Got a winner! 13
Got a winner! 13
Got a winner! 13
Got a winner! 13
Got a winner! 13
Got a winner! 17
Got a winner! 17
Got a winner! 17
Got a winner! 7
Got a winner! 7
Got a winner! 7
Got a w

In [108]:
my_board.scoreboard

array([[0., 1., 1., 1., 1.],
       [1., 1., 0., 1., 0.],
       [1., 0., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 0., 1., 1.]])

In [109]:
# Part 2 answer
print(my_sum * num)

2730
