Advent of Code 2021 - Day 5

Part 1:
Consider only horizontal and vertical lines. At how many points do at least two lines overlap?

In [24]:
import numpy as np

In [8]:
with open('input_day5.txt', 'rt') as f:
    data = f.readlines()

data = [item.rstrip() for item in data]

print(data[:10])

['578,391 -> 578,322', '274,585 -> 651,962', '482,348 -> 294,348', '682,514 -> 367,829', '180,243 -> 800,863', '850,828 -> 850,98', '698,439 -> 460,677', '518,379 -> 518,176', '486,437 -> 486,640', '730,420 -> 374,420']


In [20]:
def get_points(line):

    points_str = line.split(' -> ')

    p1 = tuple((
        int(points_str[0].split(',')[0]),
        int(points_str[0].split(',')[1]),
    ))
    p2 = tuple((
        int(points_str[1].split(',')[0]),
        int(points_str[1].split(',')[1]),
    ))

    nums = [p1[0], p1[1], p2[0], p2[1]]

    return tuple((p1, p2)), nums

points = []
values = []
for line in data:
    line_points, nums = get_points(line)
    values.extend(nums)
    points.append(line_points)

print(points[:10])
print(values[:10])

[((578, 391), (578, 322)), ((274, 585), (651, 962)), ((482, 348), (294, 348)), ((682, 514), (367, 829)), ((180, 243), (800, 863)), ((850, 828), (850, 98)), ((698, 439), (460, 677)), ((518, 379), (518, 176)), ((486, 437), (486, 640)), ((730, 420), (374, 420))]
[578, 391, 578, 322, 274, 585, 651, 962, 482, 348]


In [22]:
print(min(nums), max(nums))

17 956


In [27]:
def draw_line(field, p1, p2):

    x1, y1 = p1
    x2, y2 = p2

    if not (x1 == x2 or y1 == y2):
        return field
    
    if x1 > x2:
        x1, x2 = x2, x1
    
    if y1 > y2:
        y1, y2 = y2, y1

    field[x1:x2+1,y1:y2+1] += 1

    return field

In [34]:
field = np.zeros((1000,1000))

for point in points:
    field = draw_line(field, point[0], point[1])

overlap = np.where(field >= 2, 1, 0)

In [36]:
# Part 1 answer
print(np.sum(overlap))

5084


Part 2: Consider all of the lines. At how many points do at least two lines overlap?

In [57]:
def draw_line2(field, p1, p2):

    x1, y1 = p1
    x2, y2 = p2
        
    if x1 == x2 or y1 == y2:

        if x1 > x2:
            x1, x2 = x2, x1
        
        if y1 > y2:
            y1, y2 = y2, y1

        field[x1:x2+1,y1:y2+1] += 1

    elif abs(x2 - x1) == abs(y2 - y1):
        x, y = x1, y1

        while (x1 <= x <= x2) or (x2 <= x <= x1):
            field[x,y] += 1
            
            if x2 > x1:
                x += 1
            else:
                x-=1

            if y2 > y1:
                y += 1
            else:
                y -= 1

    else:
        return field

    return field

In [58]:
field = np.zeros((1000,1000))

for point in points:
    field = draw_line2(field, point[0], point[1])

overlap = np.where(field >= 2, 1, 0)

In [59]:
# Part 2 answer
print(np.sum(overlap))

17882


In [55]:
a = draw_line2(np.zeros((10,10)), (1,1), (5,5))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [56]:
min(3,5)

3