Advent of Code 2021 - Day 9

Part 1:
Find all of the low points on your heightmap. What is the sum of the risk levels of all low points on your heightmap?

In [2]:
import numpy as np

In [4]:
with open('input_day9.txt', 'rt') as f:
    data = f.readlines()

data = [[int(char) for char in item.rstrip()] for item in data]
data = np.array(data)
print(data)

[[7 8 5 ... 3 4 5]
 [6 7 4 ... 2 3 3]
 [5 4 3 ... 1 0 2]
 ...
 [4 5 7 ... 5 6 7]
 [5 6 8 ... 3 9 8]
 [6 7 8 ... 5 6 9]]


In [5]:
np.shape(data)

(100, 100)

In [23]:
def check_low_point(x, y, data):

    x_max, y_max = np.shape(data)
    
    point = data[x, y]
    neighbors = []

    if not x == 0:
        neighbors.append(data[x-1, y])
    if not x == x_max-1:
        neighbors.append(data[x+1, y])
    if not y == 0:
        neighbors.append(data[x, y-1])
    if not y == y_max-1:
        neighbors.append(data[x, y+1])
    
    if all([n > point for n in neighbors]):
        return point + 1
    else:
        return 0


In [24]:
x_max, y_max = np.shape(data)

cumsum=0
for x in range(x_max):
    for y in range(y_max):
        cumsum += check_low_point(x, y, data)


In [25]:
# Part 1 answer
print(cumsum)

535


Part 2: What do you get if you multiply together the sizes of the three largest basins?

In [42]:
x_max, y_max = np.shape(data)


def find_low_point(x, y, data):
    
    point_val = data[x, y]
    neighbors = []

    if not x == 0:
        neighbors.append(data[x-1, y])
    if not x == x_max-1:
        neighbors.append(data[x+1, y])
    if not y == 0:
        neighbors.append(data[x, y-1])
    if not y == y_max-1:
        neighbors.append(data[x, y+1])
    
    if all([n > point_val for n in neighbors]):
        return True
    else:
        return False


def find_basin(x, y, data, neighbors):
    
    point_val = data[x, y]

    new_neighbors = []
    
    if not x == 0:
        add_if_ok(x-1, y, new_neighbors, point_val)

    if not x == x_max-1:
        add_if_ok(x+1, y, new_neighbors, point_val)

    if not y == 0:
        add_if_ok(x, y-1, new_neighbors, point_val)

    if not y == y_max-1:
        add_if_ok(x, y+1, new_neighbors, point_val)
    
    if new_neighbors:
        for point in new_neighbors:
            neighbors.append(point)
            find_basin(point[0], point[1], data, neighbors)


def add_if_ok(x_neighbor, y_neighbor, neighbors, point_val):

    neighbor_val = data[x_neighbor, y_neighbor]

    if neighbor_val > point_val and neighbor_val != 9:
        neighbors.append((x_neighbor, y_neighbor))

In [43]:
low_points = []

for x in range(x_max):
    for y in range(y_max):
        if find_low_point(x, y, data):
            low_points.append((x,y))

In [58]:
basin_sizes = []
for point in low_points:
    neighbors = [point]
    find_basin(point[0], point[1], data, neighbors)
    basin_sizes.append(len(set(neighbors)))

# set(neighbors)
top = sorted(basin_sizes, reverse=True)[:3]

In [59]:
# Part 2 answer
print(top[0] * top[1] * top[2])

1122700
